using System;
using System.Collections.Generic;
using System.IO;

using Common.Logging;

namespace Mochify.Simile.Core.Utils
{
    public class TestCaseGenerator
    {
        private IAssetManager _fileManager;
        private static readonly ILog _log = LogManager.GetCurrentClassLogger();

        public TestCaseGenerator(IAssetManager fileManager)
        {
            _fileManager = fileManager;
        }

        /// <summary>
        /// This function consumes an iterator over ShellTestCase objects
        /// and yields an iterator over the TestCase objects generated by them.
        /// </summary>
        /// <param name="shells"></param>
        /// <returns></returns>
        public IEnumerable<TestCase> GenerateTestCases(IEnumerable<ShellTestCase> shells)
        {
            int c = 0;
            foreach (var shell in shells)
            {
                ++c;
                TestCase tc = null;
                try
                {
                    tc = Generate(shell);
                }
                catch (Exception e)
                {
                    _log.WarnFormat("Problem adding test case {0}: {1}", c, shell.ReferenceLocation);
                    _log.Debug(e.Message, e);
                    continue;
                }
                yield return tc;
            }
        }

        public TestCase Generate(ShellTestCase shell)
        {
            // we have to do something to obtain the reference image
            // and save it to the 'reference' location
            string copiedName = _fileManager.FetchToRandomFilename(shell.ReferenceLocation, shell.ReferenceSavePath);

            var tc = new TestCase
            {
                SourceLocation = shell.ReferenceLocation,
                ReferenceLocation = Path.Combine(shell.ReferenceSavePath, copiedName),
                Type = shell.Type,
                Release = shell.Release,
                Description = shell.Description,
                DateAdded = DateTime.Now,
                DateModified = DateTime.Now
            };

            return tc;
        }
    }
}
